name: Publish image to Docker Hub
on: push
jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: build
              run: |
                docker build -f users.dockerfile -t shuaibu12345/users:latest .
            - name: publish
              run: |
                docker login -u shuaibu12345 -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push shuaibu12345/users:latest